// compile_requirements — pure function that reads prd/*.md and produces requirements.md
// Idempotent: running twice produces identical output.
// Feature and Rule IDs are not renumbered — F-1 from two PRDs both appear in output.
import { existsSync, readFileSync, readdirSync, writeFileSync } from "fs";
import { basename, join } from "path";

export interface CompileResult {
  specPath: string;
  prdFiles: string[];
  outputPath: string;
  featuresCompiled: number;
  rulesCompiled: number;
  written: boolean;
  skippedReason?: string;
  compiledText: string;
}

function readFile(path: string): string {
  try { return readFileSync(path, "utf-8"); } catch { return ""; }
}

function stripTitle(text: string): string {
  // Remove the first heading line if it matches "# PRD ..." or "# ..."
  return text.replace(/^\s*#[^\n]*\n/, "").trimStart();
}

function countPattern(text: string, pattern: RegExp): number {
  const re = new RegExp(pattern.source, "gim");
  return (text.match(re) ?? []).length;
}

export function compileRequirements(specPath: string, write = false): CompileResult {
  const prdDir = join(specPath, "prd");
  const outputPath = join(specPath, "requirements.md");

  if (!existsSync(prdDir)) {
    return {
      specPath,
      prdFiles: [],
      outputPath,
      featuresCompiled: 0,
      rulesCompiled: 0,
      written: false,
      skippedReason: "prd/ directory not found",
      compiledText: "",
    };
  }

  let fileNames: string[];
  try {
    fileNames = readdirSync(prdDir).filter((f) => f.endsWith(".md")).sort();
  } catch {
    fileNames = [];
  }

  if (fileNames.length === 0) {
    return {
      specPath,
      prdFiles: [],
      outputPath,
      featuresCompiled: 0,
      rulesCompiled: 0,
      written: false,
      skippedReason: "prd/ directory contains no .md files",
      compiledText: "",
    };
  }

  const sections = fileNames.map((name) => {
    const content = stripTitle(readFile(join(prdDir, name)));
    return `<!-- Source: prd/${name} -->\n\n${content}`;
  });

  const preamble = [
    "# Requirements",
    "",
    "<!-- AUTO-GENERATED by compile_requirements. Source: prd/ directory. Do not edit directly. -->",
    "",
  ].join("\n");

  const compiledText = preamble + sections.join("\n\n---\n\n");

  const featuresCompiled = countPattern(compiledText, /^#{1,3}\s+Feature\s+F-\d+/m);
  const rulesCompiled = countPattern(compiledText, /Rule\s+R-\d+/);

  if (write) {
    writeFileSync(outputPath, compiledText, "utf-8");
  }

  return {
    specPath,
    prdFiles: fileNames.map((f) => `prd/${f}`),
    outputPath,
    featuresCompiled,
    rulesCompiled,
    written: write,
    compiledText,
  };
}
